### ISSUE TITLE
Error appears when running getShodan.py

### ISSUE THREAD

**Issue by Visalyputra** [dn9uy3n/Get-Shodan#1]
when i type this one python3 getShodan.py -h
i got this error 

File "getShodan.py", line 30

SyntaxError: invalid syntax

and when i type this one python getShodan.py -h

i got this error

Traceback (most recent call last):
  File "getShodan.py", line 2, in <module>
    import shodan
ImportError: No module named shodan

i have installed the shodan module and this error still appear. 

Can you help me with this one? on how to solve this problem?

**Comment by fox4914** [comment]
Please make the download by country (**--country** ). The lack of this function is a big minus. Thanks

**Comment by fox4914** [comment]
> when i type this one python3 getShodan.py -h
> i got this error
> 
> File "getShodan.py", line 30
> 
> SyntaxError: invalid syntax
> 
> and when i type this one python getShodan.py -h
> 
> i got this error
> 
> Traceback (most recent call last):
> File "getShodan.py", line 2, in
> import shodan
> ImportError: No module named shodan
> 
> i have installed the shodan module and this error still appear.
> 
> Can you help me with this one? on how to solve this problem?

`pip` install shodan
